Personal-portfolio :
Tommymarvel/personal-portfolio pull request #1
Opened 2022-06-01 09:00 UTC by Tommymarvel

## Personal portfolio mobile version skeleton.

In this personal portfolio mobile version skeleton:

- Added a toolbar and headline text.

2022-06-01 16:49 UTC, vechicin requested changes
# Hi @Tommymarvel  ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good PR title/description
- [x] Good commit history
- [x] Correct GitHub Flow

## Required Changes ♻️

- [ ] You are missing a professional README. Kindly fix this as it is part of the [general requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md#general-requirements). You should follow [this template](https://github.com/microverseinc/readme-template)

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 16:49 UTC, vechicin commented on style.css
> +}
Your hamburger button is a little too big. Kindly fix that as matching the template design is a project requirement.

2022-06-01 16:49 UTC, vechicin commented on index.html
> +    <main id="intro_Section">
According to the project requirements, this should be a `<section>` tag. Kindly fix this.

<img width="302" alt="Screen Shot 2022-06-01 at 11 36 55" src="https://user-images.githubusercontent.com/82426682/171455757-e068da91-9f91-4293-8e42-4850e71c748e.png">

2022-06-02 13:47 UTC, arslanbisharat requested changes
Hi @Tommymarvel, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 11:16 UTC, muneebulrehman commented on index.html
> +      </nav>
Hey, while fixing the previously raised issues, your navbar is broken. There is no top padding/margin as in the Figma template. Have a look at your application. Kindly fix it. Also, make the logo and hamburger icon evenly spaced. I would look much better that way. 🙂
![image](https://user-images.githubusercontent.com/33268927/171842774-27f8293a-c2c6-4eff-b7a7-5cade5498443.png)

2022-06-03 11:16 UTC, muneebulrehman commented on index.html
> +    <main id="intro_Section">
@Tommymarvel , kindly follow up with the required changes. Your navbar should be enclosed in a `header` tag and headline section should be wrapped in a `section` tag.

2022-06-03 11:18 UTC, muneebulrehman requested changes
Hi @Tommymarvel , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. You are almost there.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 19:45 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Tommymarvel 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 19:45 UTC, tresorsawasawa commented on style.css
> +  /* background-color: red; */
# [OPTIONAL]
- [ ] Kindly remove all commented code to make you code clear and clean.

2022-06-04 20:16 UTC, merged